"""
Gives the script generator a memory of what the show recently said.

Each episode is generated by a separate API call with no knowledge of the
others, so without this the model converges on the same openers, bits and
sign-offs. Here we load the full text of the last few episodes from the same
season and hand them back as an "avoid reusing this" block.

Plain code, no network: everything comes from data/schedule.json and the
script.txt files already saved under data/episodes/.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"

# How many previous full scripts to show the model. Each is ~800 words, so 3 is
# roughly 3k tokens: cheap, and enough to see a pattern across episodes.
RECENT_SCRIPTS_COUNT = 3


def load_recent_scripts(schedule, current_game_id, season, count=RECENT_SCRIPTS_COUNT, data_dir=None):
    """Return the last `count` generated episodes strictly BEFORE the current
    game, from the same season, oldest first.

    Each item: {"game_id", "opponent", "date", "result_summary", "script"}.

    Fails safe: if the season is unknown or the current game isn't in the
    schedule, returns [] (showing no memory is better than showing the wrong
    season's or a later game's scripts). Games on or after the current game are
    never included, so re-generating an old game in test mode can't see its own
    future.
    """
    if season is None:
        return []
    data_dir = Path(data_dir or DATA_DIR)

    all_games = sorted(schedule["games"], key=lambda g: g["starts_at"])
    current_index = next(
        (i for i, g in enumerate(all_games) if g["game_id"] == current_game_id), None
    )
    if current_index is None:
        return []

    recent = []
    for g in reversed(all_games[:current_index]):
        if len(recent) >= count:
            break
        if g.get("season") != season or not g.get("episode_generated"):
            continue
        episode_dir = data_dir / "episodes" / g["game_id"]
        script_path = episode_dir / "script.txt"
        if not script_path.exists():
            continue

        summary = {}
        summary_path = episode_dir / "summary.json"
        if summary_path.exists():
            try:
                summary = json.loads(summary_path.read_text())
            except ValueError:
                summary = {}

        recent.append({
            "game_id": g["game_id"],
            "opponent": summary.get("opponent") or g.get("opponent"),
            "date": summary.get("date") or g["starts_at"][:10],
            "result_summary": summary.get("result_summary"),
            "script": script_path.read_text().strip(),
        })

    recent.reverse()  # oldest first
    return recent


def format_recent_scripts(recent):
    """Prompt section listing recent scripts for avoidance. Returns "" when
    there is nothing to show (first episode of a season)."""
    if not recent:
        return ""

    lines = [
        "## Recent Episodes (avoid repeating these)",
        "",
        f"Below are the full scripts of the last {len(recent)} episode(s), oldest first. "
        "They are here so you can steer AWAY from them, not so you can imitate them.",
        "",
        "- Do not reuse their jokes, running bits, catchphrases, reaction lines, "
        "opening or closing lines, transitions, or overall shape. A joke or exchange "
        "that already ran is spent: find a new one.",
        "- If the same kind of line or beat shows up in more than one of these "
        "scripts, treat it as a tic and retire it.",
        "- The exception is continuity. Season storylines, predictions, and the "
        "hosts' own earlier claims may be referred back to when that genuinely "
        "serves tonight's episode, in fresh words.",
        "- Nothing below is a fact about tonight's game.",
        "",
    ]
    for ep in recent:
        header = f"### Vs {ep['opponent']} ({ep['date']})"
        if ep.get("result_summary"):
            header += f" — {ep['result_summary']}"
        lines.append(header)
        lines.append("```text")
        lines.append(ep["script"])
        lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
